spring:
  application:
    name: menstrualcyclebot

  config:
    import: "application-secrets.yml"  # Импортируем файл с секретами

  datasource:
    url: jdbc:postgresql://localhost:5432/menstrualcyclebotdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
