spring:
  application:
    name: menstrualcyclebot

  config:
    import: "application-secrets.yml"  # Импортируем файл с секретами

  datasource:
    url: jdbc:postgresql://localhost:5432/menstrualcyclebotdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Показывает SQL-запросы в логах, что поможет в отладке
    properties:
      hibernate:
        format_sql: true  # Форматирует SQL-запросы в более читаемом виде
