spring:
  application:
    name: menstrualcyclebot

  config:
    import: "application-secrets.yml"  # Импортируем файл с секретами

  datasource:
    url: jdbc:postgresql://localhost:5432/menstrualcyclebotdb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Форматируем SQL-запросы для удобства
    show-sql: true  # Включаем вывод SQL-запросов в лог

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG  # Логирование SQL-запросов на уровне DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE  # Логирование параметров запросов
    org.springframework.orm.jpa: DEBUG  # Логирование JPA на уровне DEBUG
    org.springframework.transaction: DEBUG  # Логирование транзакций
